/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package openapi_schemas

import spock.lang.Specification

class AppTest extends Specification {

  def "application has a greeting"()
  {
    setup:
      def app = new App()

    when:
      app.doValidation()

    then:
      true
      //result != null
  }
}
